# 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "ServiceAccountIssuerDiscovery": true
networking:
  apiServerAddress: 0.0.0.0
  apiServerPort: 6443
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: "kindest/node:v1.22.17@sha256:9af784f45a584f6b28bce2af84c494d947a05bd709151466489008f80a9ce9d5"
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        api-audiences: "kubernetes.svc.default"
        service-account-api-audiences: "cluster.identifier.kubernetes.domain"
        service-account-issuer: "https://CLOUDFRONT_DOMAIN_NAME_PLACEHOLDER/cluster/my-oidc-cluster"
        service-account-jwks-uri: "https://CLOUDFRONT_DOMAIN_NAME_PLACEHOLDER/cluster/my-oidc-cluster/openid/v1/jwks"
        service-account-signing-key-file: "/etc/kubernetes/pki/sa.key"
        